project_id = "chswulyeiyeuiawgjxze"

[functions.compute-create-user]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true
